/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assets */
        get: operations["assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chain */
        get: operations["chain_api_v1_assets__symbol__chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecasts */
        get: operations["forecasts_api_v1_assets__symbol__forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/headlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headlines */
        get: operations["headlines_api_v1_assets__symbol__headlines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_v1_assets__symbol__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scores */
        get: operations["scores_api_v1_assets__symbol__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/spot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spot */
        get: operations["spot_api_v1_assets__symbol__spot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formulas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Formulas */
        get: operations["formulas_api_v1_formulas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro Forecasts */
        get: operations["macro_forecasts_api_v1_macro_forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetHistory */
        AssetHistory: {
            /** Formula */
            formula: string;
            /** Points */
            points: components["schemas"]["ScorePoint"][];
            scale: components["schemas"]["Scale"];
            /** Symbol */
            symbol: string;
        };
        /** AssetOut */
        AssetOut: {
            /** Economies */
            economies: string[];
            /** Kind */
            kind: string;
            /** Symbol */
            symbol: string;
            /** Tradingview */
            tradingview: string | null;
        };
        /**
         * AssetSummary
         * @description One overview card.
         */
        AssetSummary: {
            /** Band */
            band: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Delta */
            delta: number | null;
            /** Event Risk */
            event_risk: number;
            /** Formula */
            formula: string;
            /** Kind */
            kind: string;
            /** Score */
            score: number;
            /** Sparkline */
            sparkline: number[];
            /** Symbol */
            symbol: string;
        };
        /** CalendarEvent */
        CalendarEvent: {
            /** Actual */
            actual: number | null;
            /** Category */
            category: string;
            /** Consensus */
            consensus: number | null;
            /** Country */
            country: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Event */
            event: string;
            /** Id */
            id: string;
            /** Importance */
            importance: number;
            /** Previous */
            previous: number | null;
        };
        /** ChainPoint */
        ChainPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
        /** ChainSeries */
        ChainSeries: {
            /** Label */
            label: string;
            /** Metric */
            metric: string;
            /** Points */
            points: components["schemas"]["ChainPoint"][];
            /** Source */
            source: string;
        };
        /**
         * ForecastMacro
         * @description Like ForecastAsset, but about an economy: a policy rate, CPI, GDP or unemployment.
         */
        ForecastMacro: {
            /** Confidence */
            confidence: number;
            /** Economy */
            economy: string;
            /**
             * Horizon Date
             * Format: date
             */
            horizon_date: string;
            /** Horizon Label */
            horizon_label: string;
            /** Id */
            id: string;
            /** Institution */
            institution: string;
            /** Metric */
            metric: string;
            /** Model */
            model: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Source Kind */
            source_kind: string;
            /** Source Url */
            source_url: string;
            /** Value */
            value: number;
        };
        /** ForecastPanel */
        ForecastPanel: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Macro */
            macro: components["schemas"]["MacroForecastRow"][];
            /** Medians */
            medians: components["schemas"]["MedianRow"][];
            /** Rows */
            rows: components["schemas"]["ForecastRow"][];
            /** Spot */
            spot: number | null;
            /** Symbol */
            symbol: string;
        };
        /** ForecastRow */
        ForecastRow: {
            /** Confidence */
            confidence: number;
            /**
             * Horizon Date
             * Format: date
             */
            horizon_date: string;
            /** Horizon Label */
            horizon_label: string;
            /** Institution */
            institution: string;
            /** Previous Value */
            previous_value: number | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Value */
            value: number;
            /** Vs Spot */
            vs_spot: number | null;
        };
        /** FormulasOut */
        FormulasOut: {
            /** Default */
            default: string;
            /** Known */
            known: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadlineView
         * @description A tagged headline and how much it weighed on the score.
         */
        HeadlineView: {
            /** Confidence */
            confidence: number;
            /** Direction */
            direction: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Source */
            source: string;
            /** Source Weight */
            source_weight: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Weight */
            weight: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Last Run */
            last_run: string | null;
            /** Status */
            status: string;
        };
        /** MacroForecastRow */
        MacroForecastRow: {
            /** Confidence */
            confidence: number;
            /** Economy */
            economy: string;
            /**
             * Horizon Date
             * Format: date
             */
            horizon_date: string;
            /** Horizon Label */
            horizon_label: string;
            /** Institution */
            institution: string;
            /** Metric */
            metric: string;
            /** Previous Value */
            previous_value: number | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Value */
            value: number;
        };
        /** MedianRow */
        MedianRow: {
            /**
             * Horizon Date
             * Format: date
             */
            horizon_date: string;
            /** Value */
            value: number;
        };
        /** ReportOut */
        ReportOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Formula */
            formula: string;
            /** Report Md */
            report_md: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * Scale
         * @description Where a formula's scores live: the ends, the neutral point and the four band edges.
         */
        Scale: {
            /** Edges */
            edges: [
                number,
                number,
                number,
                number
            ];
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Neutral */
            neutral: number;
        };
        /** ScorePoint */
        ScorePoint: {
            /** Band */
            band: string;
            /** Components */
            components: {
                [key: string]: number;
            };
            /**
             * Date
             * Format: date
             */
            date: string;
            /** N Events */
            n_events: number;
            /** N News */
            n_news: number;
            /** Score */
            score: number;
        };
        /**
         * SpotPrice
         * @description One daily close, for display next to forecasts only; never a formula input.
         */
        SpotPrice: {
            /** Asset */
            asset: string;
            /** Close */
            close: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assets_api_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
        };
    };
    chain_api_v1_assets__symbol__chain_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainSeries"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecasts_api_v1_assets__symbol__forecasts_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                min_confidence?: number | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPanel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    headlines_api_v1_assets__symbol__headlines_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadlineView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_assets__symbol__report_get: {
        parameters: {
            query?: {
                date?: string | null;
                formula?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scores_api_v1_assets__symbol__scores_get: {
        parameters: {
            query?: {
                formula?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spot_api_v1_assets__symbol__spot_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotPrice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                min_importance?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    formulas_api_v1_formulas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormulasOut"];
                };
            };
        };
    };
    macro_forecasts_api_v1_macro_forecasts_get: {
        parameters: {
            query: {
                economy: string;
                metric?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastMacro"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
