"""news analyzed_at

Revision ID: c92c21e082d1
Revises: ff61e22298ec
Create Date: 2026-09-20 11:59:07.173607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c92c21e082d1"
down_revision: str | Sequence[str] | None = "ff61e22298ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
    # every stored item was tagged by the run that fetched it, before fetch and run split
    op.execute("UPDATE news SET analyzed_at = fetched_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("analyzed_at")

    # ### end Alembic commands ###
