"""news tags model and prompt version

Revision ID: ff61e22298ec
Revises: 9bbb45ea6917
Create Date: 2026-09-17 15:47:48.801500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff61e22298ec"
down_revision: str | Sequence[str] | None = "9bbb45ea6917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_tags", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("model", sa.String(length=128), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("prompt_version", sa.String(length=16), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_tags", schema=None) as batch_op:
        batch_op.drop_column("prompt_version")
        batch_op.drop_column("model")

    # ### end Alembic commands ###
