from collections.abc import Iterable
from datetime import date, datetime
from typing import Protocol, runtime_checkable

from manc.models import CalendarEvent, IndexScore, NewsItem, NewsTag


@runtime_checkable
class Store(Protocol):
    """Persistence boundary. Every save is an upsert; every load returns sorted by time."""

    def save_news(self, items: Iterable[NewsItem]) -> None: ...
    def save_tags(self, tags: Iterable[NewsTag]) -> None: ...
    def save_events(self, events: Iterable[CalendarEvent]) -> None: ...
    def save_score(self, score: IndexScore, report_md: str = "") -> None: ...

    def load_news(self, since: datetime) -> list[NewsItem]: ...
    def load_tagged_news(self, asset: str, since: datetime) -> list[tuple[NewsItem, NewsTag]]: ...
    def load_events(self, start: date, end: date) -> list[CalendarEvent]: ...
    def load_scores(self, asset: str, formula: str, start: date, end: date) -> list[IndexScore]: ...
